# Generated by Django 2.2.25 on 2022-01-13 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220113_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='record',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован?'),
        ),
        migrations.AlterField(
            model_name='record',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Размещен'),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
    ]
